"""Pre-flight panel and agentic ``yikes.toml`` setup helpers.

Before a one-word launcher (``yikes claude`` / ``yikes codex``) hands the screen
to the backend's interactive UI, it prints a short panel so the user can see the
session, mapped ports, and how to leave/return. The same module holds the small
pure helpers used to turn a backend's repository scan into a ``yikes.toml``.
"""

from __future__ import annotations

import json
import re

SCAN_PROMPT = (
    "Inspect this repository and determine which localhost HTTP ports its app or "
    "dev servers are configured to serve. Look at package.json scripts, "
    "vite/next/webpack/astro config, docker-compose files, Dockerfile EXPOSE "
    "directives, .env files, Procfile, and any framework config. "
    "Respond with ONE JSON object and nothing else, in this exact shape: "
    '{"ports": [<int>, ...], "backend": "claude" | "codex" | null, '
    '"notes": "<one short sentence>"}. '
    "Use an empty list when the project serves no HTTP ports. Do not wrap the "
    "JSON in code fences or add any prose around it."
)


def render_panel(
    *,
    backend: str,
    name: str,
    location: str,
    cwd: str,
    reused: bool,
    config_source: str | None,
    ports: tuple[tuple[str, str], ...],
    isolated: bool,
) -> str:
    """Return the compact pre-flight panel shown before attaching."""
    state = "reattach" if reused else "new"
    config = config_source if config_source else "not configured yet"
    lines = [
        f"  yikes! · {backend} · {location} · {cwd}",
        f"  session   {name}   ({state})",
        f"  config    {config}",
    ]
    if isolated:
        port_text = ", ".join(host for host, _ in ports) if ports else "none"
        lines.append(f"  ports     {port_text}")
    lines.extend(
        [
            "",
            f"  detach    Ctrl-b d        reattach   yikes {backend}",
            f"  close     yikes close {name}",
            "",
            "  [Enter] start   ·   [s] scan & set up yikes.toml   ·   [q] cancel",
        ]
    )
    return "\n".join(lines)


def parse_scan_result(text: str) -> dict[str, object]:
    """Extract the first JSON object from a backend reply.

    Tolerates surrounding prose or code fences. Raises ``ValueError`` when no
    JSON object can be parsed.
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match is None:
        raise ValueError("no JSON object found in scan result")
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError as exc:
        raise ValueError(f"scan result was not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("scan result JSON was not an object")
    return data


def ports_from_scan(data: dict[str, object]) -> tuple[int, ...]:
    """Pull a clean, de-duplicated list of port numbers out of scan JSON."""
    raw = data.get("ports")
    if not isinstance(raw, list):
        return ()
    ports: list[int] = []
    for item in raw:
        try:
            port = int(item)
        except (TypeError, ValueError):
            continue
        if 1 <= port <= 65535 and port not in ports:
            ports.append(port)
    return tuple(ports)


def synthesize_config(ports: tuple[int, ...], backend: str | None) -> str:
    """Build ``yikes.toml`` text from detected ports and an optional backend."""
    lines = ["# yikes! project defaults (generated by `yikes setup`)."]
    if backend in ("claude", "codex"):
        lines.append(f'backend  = "{backend}"')
    if ports:
        port_list = ", ".join(str(port) for port in ports)
        lines.append("isolated = false")
        lines.append(f"ports    = [{port_list}]")
    else:
        lines.append("isolated = false")
        lines.append("# ports  = [8080]  # no HTTP ports detected")
    return "\n".join(lines) + "\n"
